from typing import Protocol


class ObjectStore(Protocol):
    def put_image(self, data: bytes, *, content_type: str) -> str: ...

    def get_uri(self, uri: str) -> str: ...

    def delete(self, uri: str) -> None: ...

    def open(self, uri: str) -> bytes: ...
