"""shopping list and item

Revision ID: 05d94948c8d5
Revises: 2503bceffa1d
Create Date: 2026-07-14 15:20:44.379814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d94948c8d5'
down_revision: Union[str, Sequence[str], None] = '2503bceffa1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list',
    sa.Column('shopping_list_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('shopping_list_id'),
    schema='pantryops'
    )
    op.create_index(op.f('ix_pantryops_shopping_list_user_id'), 'shopping_list', ['user_id'], unique=False, schema='pantryops')
    op.create_table('shopping_item',
    sa.Column('shopping_item_id', sa.Uuid(), nullable=False),
    sa.Column('shopping_list_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('desired_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_label', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('crossed_off', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['pantryops.shopping_list.shopping_list_id'], ),
    sa.PrimaryKeyConstraint('shopping_item_id'),
    sa.UniqueConstraint('shopping_list_id', 'canonical_name', name='uq_shopping_item_per_list'),
    schema='pantryops'
    )
    op.create_index(op.f('ix_pantryops_shopping_item_shopping_list_id'), 'shopping_item', ['shopping_list_id'], unique=False, schema='pantryops')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_pantryops_shopping_item_shopping_list_id'), table_name='shopping_item', schema='pantryops')
    op.drop_table('shopping_item', schema='pantryops')
    op.drop_index(op.f('ix_pantryops_shopping_list_user_id'), table_name='shopping_list', schema='pantryops')
    op.drop_table('shopping_list', schema='pantryops')
    # ### end Alembic commands ###
