"""pantry ledger initial

Revision ID: 2503bceffa1d
Revises: 7c9d1738e9ca
Create Date: 2026-07-13 17:31:52.432298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2503bceffa1d'
down_revision: Union[str, Sequence[str], None] = '7c9d1738e9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_item',
    sa.Column('pantry_item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity_type', sa.String(), nullable=False),
    sa.Column('unit_label', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('estimated_use_by', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('needs_user_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pantry_item_id'),
    schema='pantryops'
    )
    op.create_index(op.f('ix_pantryops_pantry_item_status'), 'pantry_item', ['status'], unique=False, schema='pantryops')
    op.create_index(op.f('ix_pantryops_pantry_item_user_id'), 'pantry_item', ['user_id'], unique=False, schema='pantryops')
    op.create_table('ledger_change_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pantry_item_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['pantryops.pantry_item.pantry_item_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pantryops'
    )
    op.create_index(op.f('ix_pantryops_ledger_change_log_pantry_item_id'), 'ledger_change_log', ['pantry_item_id'], unique=False, schema='pantryops')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pantryops_ledger_change_log_pantry_item_id'), table_name='ledger_change_log', schema='pantryops')
    op.drop_table('ledger_change_log', schema='pantryops')
    op.drop_index(op.f('ix_pantryops_pantry_item_user_id'), table_name='pantry_item', schema='pantryops')
    op.drop_index(op.f('ix_pantryops_pantry_item_status'), table_name='pantry_item', schema='pantryops')
    op.drop_table('pantry_item', schema='pantryops')
    # ### end Alembic commands ###
